version: "3.8"
services:
  database:
    image: mysql:8.0.37
    restart: always
    environment:
      - MYSQL_DATABASE=independent_chain_bot
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=7g2WLtbd7zYlce8G
      - MYSQL_PASSWORD=7g2WLtbd7zYlce8G
    volumes:
      - database_volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=database
      - MYSQL_ROOT_PASSWORD=7g2WLtbd7zYlce8G
  bot:
    restart: always
    build: /
    command: python ./main.py
volumes:
  database_volume:
